version: '3.9'

services:
  quartermaster-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: quartermaster-dev:latest
    ports:
      - '5173:5173'
      - '4000:4000'
    env_file:
      - .env
    environment:
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev:docker
